	SELECT
    SONG_ID ,
	SONG_NAME as SONG,
	COVER ,
	SPOTIFY_SONG_ID ,
	EARLIEST_SHOW_DATE ,
	LATEST_SHOW_DATE ,
	EARLIEST_SHOW_CITY ,
	EARLIEST_SHOW_STATE ,
	EARLIEST_VENUE ,
	LATEST_VENUE ,
	LATEST_SHOW_CITY ,
	LATEST_SHOW_STATE ,
	PLAYS ,
	LAST_30_PLAYS ,
	LAST_15_PLAYS ,
	YEAR_OVER_YEAR 
    FROM PHISH_SONGS
