
gateways:
  snowflake:
    connection:
      type: snowflake
      account: ${{ SNOWFLAKE_ACCOUNT }}
      user: ${{ SNOWFLAKE_USERNAME }}
      password: ${{ SNOWFLAKE_PASSWORD }}
      database: ${{ SNOWFLAKE_DATABASE }}
      warehouse: ${{ SNOWFLAKE_WAREHOUSE }}
      role: ${{ SNOWFLAKE_ROLE }}


    state_connection:
      type: duckdb
      database: snowflake_state.db

default_gateway: snowflake

model_defaults:
  dialect: snowflake
  start: 2024-11-16


